// `android/` is generated by `expo prebuild` and gitignored, so release signing and the
// build number can't be edited in checked-in Gradle files. This plugin patches them into
// the generated app/build.gradle. Everything is driven by Gradle properties (-P...) and
// falls back to the debug keystore and the app.json version when they aren't passed, so a
// plain local prebuild + build keeps working.
//
//   -PSATTLE_UPLOAD_STORE_FILE / _STORE_PASSWORD / _KEY_ALIAS / _KEY_PASSWORD  release signing
//   -PSATTLE_VERSION_CODE / -PSATTLE_VERSION_NAME                              store version
const { withAppBuildGradle } = require('expo/config-plugins');

function patch(contents, pattern, replacement, what) {
  if (!pattern.test(contents)) {
    // A silent miss would ship a release signed with the debug key, so fail the prebuild.
    throw new Error(`withAndroidReleaseSigning: could not find ${what} in app/build.gradle`);
  }
  return contents.replace(pattern, replacement);
}

module.exports = function withAndroidReleaseSigning(config) {
  return withAppBuildGradle(config, (cfg) => {
    let gradle = cfg.modResults.contents;
    if (gradle.includes('SATTLE_UPLOAD_STORE_FILE')) return cfg;

    gradle = patch(
      gradle,
      /versionCode \d+/,
      // Parenthesised: Groovy reads `versionCode (x).toInteger()` as `versionCode(x).toInteger()`.
      `versionCode((findProperty('SATTLE_VERSION_CODE') ?: '1').toInteger())`,
      'versionCode',
    );
    gradle = patch(
      gradle,
      /versionName "([^"]*)"/,
      `versionName(findProperty('SATTLE_VERSION_NAME') ?: "$1")`,
      'versionName',
    );
    gradle = patch(
      gradle,
      /signingConfigs \{\n(\s*)debug \{/,
      `signingConfigs {
$1release {
$1    if (findProperty('SATTLE_UPLOAD_STORE_FILE')) {
$1        storeFile file(findProperty('SATTLE_UPLOAD_STORE_FILE'))
$1        storePassword findProperty('SATTLE_UPLOAD_STORE_PASSWORD')
$1        keyAlias findProperty('SATTLE_UPLOAD_KEY_ALIAS')
$1        keyPassword findProperty('SATTLE_UPLOAD_KEY_PASSWORD')
$1    }
$1}
$1debug {`,
      'signingConfigs.debug',
    );
    gradle = patch(
      gradle,
      /(release \{[^}]*?)signingConfig signingConfigs\.debug/,
      `$1signingConfig findProperty('SATTLE_UPLOAD_STORE_FILE') ? signingConfigs.release : signingConfigs.debug`,
      'the release buildType signingConfig',
    );

    cfg.modResults.contents = gradle;
    return cfg;
  });
};
