// iOS 27 stops an app at launch unless it uses the scene life cycle, and the Expo 57
// template still creates its window in the app delegate. `ios/` is generated by
// `expo prebuild` and gitignored, so this plugin patches the generated project: the scene
// manifest goes into Info.plist, and AppDelegate.swift leaves the window to Expo's
// ExpoAppSceneDelegate, which creates it for the scene and starts React Native in it.
//
// A template that already does this is left alone, so the plugin can stay through an
// Expo upgrade and be removed afterwards.
const { withAppDelegate, withInfoPlist } = require('expo/config-plugins');

function patch(contents, pattern, replacement, what) {
  if (!pattern.test(contents)) {
    // A silent miss would build an app that iOS 27 kills on launch, so fail the prebuild.
    throw new Error(`withIosSceneLifecycle: could not find ${what} in AppDelegate.swift`);
  }
  return contents.replace(pattern, replacement);
}

module.exports = function withIosSceneLifecycle(config) {
  config = withInfoPlist(config, (cfg) => {
    cfg.modResults.UIApplicationSceneManifest ??= {
      UIApplicationSupportsMultipleScenes: false,
      UISceneConfigurations: {
        UIWindowSceneSessionRoleApplication: [
          {
            UISceneConfigurationName: 'Default Configuration',
            UISceneDelegateClassName: '$(PRODUCT_MODULE_NAME).SceneDelegate',
          },
        ],
      },
    };
    return cfg;
  });

  return withAppDelegate(config, (cfg) => {
    let swift = cfg.modResults.contents;
    if (swift.includes('ExpoReactNativeFactoryProvider')) return cfg;

    // The scene delegate reads the factory and the module name off the app delegate.
    swift = patch(
      swift,
      /class AppDelegate: ExpoAppDelegate \{/,
      'class AppDelegate: ExpoAppDelegate, ExpoReactNativeFactoryProvider {',
      'the AppDelegate class',
    );
    // Left in, React Native would start twice: here, and again in the scene's window.
    swift = patch(
      swift,
      /#if os\(iOS\) \|\| os\(tvOS\)\r?\n\s*window = UIWindow\(frame: UIScreen\.main\.bounds\)\r?\n\s*factory\.startReactNative\([^)]*\)\r?\n#endif\r?\n(\r?\n)?/,
      '',
      'the window setup in didFinishLaunchingWithOptions',
    );
    // Declared in the app target so Info.plist can name it and the linker keeps it.
    swift = `${swift.trimEnd()}\n\nclass SceneDelegate: ExpoAppSceneDelegate {}\n`;

    cfg.modResults.contents = swift;
    return cfg;
  });
};
